# Generated by Django 5.2.8 on 2025-11-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='Title',
            new_name='title',
        ),
    ]
